<?php

declare(strict_types=1);

namespace MakinaCorpus\DbToolsBundle\Anonymizer\Core;

use MakinaCorpus\DbToolsBundle\Anonymizer\AbstractMultipleColumnAnonymizer;
use MakinaCorpus\DbToolsBundle\Attribute\AsAnonymizer;

/**
 * Anonymized a complete address with a sample of 500 dumb french addresses.
 *
 * This anonymizer handle:
 *  - country: The country. For example, France.
 *  - locality: The locality in which the street address is,
 *    and which is in the region. For example, Nantes.
 *  - region: The region in which the locality is, and which is in the country.
 *    For example, Pays de la Loire or another appropriate first-level Administrative division.
 *  - postal_code: The postal code. For example, 44000.
 *  - street_address: The street address. For example, 5 rue de la Paix.
 *  - secondary_address: Additional information (apartment, block)
 *
 * Sample from https://randommer.io/random-address
 */
#[AsAnonymizer(
    name: 'address',
    pack: 'fr_fr',
    description: <<<TXT
    Anonymize a mutlicolumn postal address.
    Map columns for each part with options ('country', 'locality', 'region', 'postal_code', 'street_address', 'secondary_address')
    TXT
)]
class AddressAnonymizer extends AbstractMultipleColumnAnonymizer
{
    /**
     * @inheritdoc
     */
    protected function getColumnNames(): array
    {
        return [
            'street_address',
            'secondary_address',
            'postal_code',
            'locality',
            'region',
            'country',
        ];
    }

    /**
     * @inheritdoc
     */
    protected function getSamples(): array
    {
        return [
            ["97 Voie Mouffetard","Apt. 469",1460,"Courbevoie","Centre","France"],
            ["7528 Avenue des Rosiers","8 étage",41449,"Beauvais","Provence-Alpes-Côte d'Azur","France"],
            ["4675 Impasse des Saussaies","7 étage",57363,"Montauban","Poitou-Charentes","France"],
            ["7 Rue Joubert","9 étage",75384,"Nanterre","Midi-Pyrénées","France"],
            ["9 Allée Saint-Dominique","2 étage",28295,"Roubaix","Auvergne","France"],
            ["5225 Rue d'Alésia","4 étage",93796,"Argenteuil","Nord-Pas-de-Calais","France"],
            ["82 Passage d'Abbeville","Apt. 560",57995,"Mérignac","Limousin","France"],
            ["9782 Quai des Panoramas","3 étage",36187,"Antony","Corse","France"],
            ["831 Allée Pastourelle","Apt. 320",29670,"Clermont-Ferrand","Limousin","France"],
            ["8 Impasse de Tilsitt","Apt. 591",23296,"Strasbourg","Midi-Pyrénées","France"],
            ["9 Allée Molière","Apt. 800",7980,"Les Abymes","Aquitaine","France"],
            ["824 Rue Royale","Apt. 741",95218,"Rueil-Malmaison","Limousin","France"],
            ["4784 Rue du Dahomey","1 étage",71000,"Amiens","Auvergne","France"],
            ["90 Quai Monsieur-le-Prince","1 étage",45946,"Strasbourg","Bourgogne","France"],
            ["673 Allée Lepic","0 étage",80038,"Lille","Centre","France"],
            ["872 Rue Pastourelle","Apt. 150",52196,"Bourges","Nord-Pas-de-Calais","France"],
            ["2 Impasse de Tilsitt","Apt. 865",12344,"Cayenne","Champagne-Ardenne","France"],
            ["3566 Place des Grands Augustins","2 étage",60638,"Le Mans","Île-de-France","France"],
            ["140 Quai de l'Odéon","1 étage",88484,"Montreuil","Auvergne","France"],
            ["586 Allée Saint-Jacques","Apt. 235",32728,"Saint-Maur-des-Fossés","Languedoc-Roussillon","France"],
            ["6 Boulevard du Faubourg-Saint-Denis","Apt. 841",47763,"Bordeaux","Lorraine","France"],
            ["6 Avenue du Dahomey","0 étage",54145,"Lorient","Champagne-Ardenne","France"],
            ["2430 Allée du Dahomey","5 étage",59151,"Aubervilliers","Champagne-Ardenne","France"],
            ["433 Passage Zadkine","2 étage",57721,"Les Abymes","Haute-Normandie","France"],
            ["911 Avenue Saint-Honoré","Apt. 138",31595,"Mérignac","Centre","France"],
            ["73 Impasse de la Harpe","Apt. 139",81689,"Perpignan","Corse","France"],
            ["22 Impasse de Provence","0 étage",34361,"Courbevoie","Auvergne","France"],
            ["962 Place de la Chaussée-d'Antin","Apt. 333",57515,"Boulogne-Billancourt","Aquitaine","France"],
            ["0 Allée Royale","Apt. 452",78578,"Roubaix","Midi-Pyrénées","France"],
            ["970 Rue Vaneau","Apt. 102",86377,"Brest","Picardie","France"],
            ["0386 Voie d'Alésia","Apt. 064",2422,"Calais","Bourgogne","France"],
            ["007 Avenue de la Harpe","Apt. 244",95360,"Montpellier","Centre","France"],
            ["1169 Passage Saint-Jacques","0 étage",60164,"Rueil-Malmaison","Limousin","France"],
            ["4467 Rue d'Abbeville","Apt. 690",91485,"Toulouse","Franche-Comté","France"],
            ["67 Voie Saint-Honoré","8 étage",37815,"Brest","Poitou-Charentes","France"],
            ["5 Place Saint-Denis","Apt. 941",60344,"Aix-en-Provence","Languedoc-Roussillon","France"],
            ["19 Boulevard d'Abbeville","6 étage",60956,"Pau","Auvergne","France"],
            ["558 Avenue de Montmorency","5 étage",78198,"Saint-Denis","Bourgogne","France"],
            ["1123 Voie de Montmorency","3 étage",17849,"Nanterre","Centre","France"],
            ["617 Voie Du Sommerard","5 étage",58046,"Nice","Aquitaine","France"],
            ["652 Boulevard Marcadet","Apt. 378",68534,"Béziers","Nord-Pas-de-Calais","France"],
            ["225 Avenue de Tilsitt","Apt. 379",63253,"Le Tampon","Midi-Pyrénées","France"],
            ["6654 Quai de la Ferronnerie","0 étage",80655,"Cayenne","Pays de la Loire","France"],
            ["1 Impasse de Paris","Apt. 922",32478,"Chambéry","Limousin","France"],
            ["7552 Passage de la Chaussée-d'Antin","Apt. 574",64494,"Levallois-Perret","Centre","France"],
            ["745 Impasse Royale","Apt. 663",51995,"Lorient","Basse-Normandie","France"],
            ["971 Place de la Huchette","Apt. 796",47030,"Clermont-Ferrand","Haute-Normandie","France"],
            ["31 Allée des Lombards","Apt. 683",98797,"Cergy","Franche-Comté","France"],
            ["31 Rue de la Ferronnerie","7 étage",94731,"Saint-Étienne","Franche-Comté","France"],
            ["768 Rue Molière","3 étage",82721,"Saint-Denis","Corse","France"],
            ["05 Allée d'Orsel","Apt. 997",4217,"Aubervilliers","Pays de la Loire","France"],
            ["999 Place de la Chaussée-d'Antin","6 étage",14846,"Les Abymes","Limousin","France"],
            ["06 Rue d'Abbeville","1 étage",79629,"Amiens","Limousin","France"],
            ["82 Rue de Presbourg","0 étage",68817,"Hyères","Lorraine","France"],
            ["285 Impasse de la Harpe","Apt. 232",26744,"Montauban","Alsace","France"],
            ["6 Voie Saint-Séverin","7 étage",93421,"Cergy","Franche-Comté","France"],
            ["3 Passage Charlemagne","Apt. 436",56730,"Rennes","Limousin","France"],
            ["4043 Avenue de la Paix","1 étage",7883,"Valence","Picardie","France"],
            ["79 Allée Oberkampf","Apt. 341",11608,"Amiens","Limousin","France"],
            ["8469 Allée Oberkampf","Apt. 460",82746,"Calais","Champagne-Ardenne","France"],
            ["5 Voie du Faubourg-Saint-Denis","Apt. 651",77962,"Fort-de-France","Pays de la Loire","France"],
            ["7 Rue Charlemagne","Apt. 337",99280,"La Rochelle","Franche-Comté","France"],
            ["794 Boulevard de la Victoire","7 étage",86631,"Metz","Limousin","France"],
            ["717 Avenue d'Orsel","7 étage",78366,"Le Mans","Centre","France"],
            ["21 Allée d'Alésia","2 étage",60132,"Saint-Pierre","Bretagne","France"],
            ["1 Quai d'Alésia","2 étage",11202,"Marseille","Aquitaine","France"],
            ["22 Boulevard de Richelieu","9 étage",14773,"Saint-Étienne","Île-de-France","France"],
            ["9 Allée de l'Odéon","Apt. 420",13058,"Ajaccio","Île-de-France","France"],
            ["819 Allée Vaneau","1 étage",78684,"Reims","Languedoc-Roussillon","France"],
            ["0 Avenue Pierre Charron","Apt. 031",77967,"Argenteuil","Lorraine","France"],
            ["266 Passage de Paris","Apt. 644",12352,"Aulnay-sous-Bois","Poitou-Charentes","France"],
            ["4 Rue Zadkine","4 étage",99866,"Beauvais","Poitou-Charentes","France"],
            ["7 Rue Saint-Bernard","3 étage",61740,"Béziers","Rhône-Alpes","France"],
            ["5 Voie des Rosiers","8 étage",24975,"Béziers","Alsace","France"],
            ["4 Allée de la Ferronnerie","Apt. 483",88348,"Rueil-Malmaison","Picardie","France"],
            ["3603 Boulevard de la Chaussée-d'Antin","7 étage",92424,"Bourges","Bretagne","France"],
            ["390 Impasse Dauphine","Apt. 158",25470,"Villeurbanne","Corse","France"],
            ["70 Rue de Montmorency","Apt. 526",81737,"Noisy-le-Grand","Picardie","France"],
            ["486 Avenue Pierre Charron","Apt. 626",93554,"Le Mans","Haute-Normandie","France"],
            ["9622 Passage Mouffetard","Apt. 081",22585,"Troyes","Languedoc-Roussillon","France"],
            ["2 Avenue du Faubourg Saint-Honoré","Apt. 563",84845,"Calais","Auvergne","France"],
            ["4 Rue du Faubourg Saint-Honoré","8 étage",50603,"Orléans","Nord-Pas-de-Calais","France"],
            ["756 Impasse de la Paix","2 étage",82469,"Montreuil","Bourgogne","France"],
            ["63 Rue de Nesle","Apt. 116",22577,"Sarcelles","Alsace","France"],
            ["56 Place Mouffetard","Apt. 543",23435,"Montauban","Île-de-France","France"],
            ["5670 Boulevard Vaneau","Apt. 566",89600,"Angers","Corse","France"],
            ["5875 Voie de Provence","Apt. 852",34680,"Metz","Basse-Normandie","France"],
            ["4 Boulevard de Richelieu","Apt. 228",56048,"Nantes","Corse","France"],
            ["918 Rue du Faubourg-Saint-Denis","Apt. 401",54205,"Pau","Centre","France"],
            ["17 Quai Lepic","Apt. 167",1018,"Antony","Provence-Alpes-Côte d'Azur","France"],
            ["3504 Passage de la Huchette","4 étage",6767,"Clermont-Ferrand","Île-de-France","France"],
            ["772 Quai Pastourelle","6 étage",96221,"Toulouse","Bretagne","France"],
            ["0852 Avenue du Dahomey","Apt. 941",2531,"Brest","Île-de-France","France"],
            ["1 Voie de Rivoli","Apt. 409",50413,"Lille","Provence-Alpes-Côte d'Azur","France"],
            ["130 Rue Oberkampf","1 étage",98980,"Béziers","Centre","France"],
            ["627 Passage d'Argenteuil","Apt. 049",32114,"Angers","Provence-Alpes-Côte d'Azur","France"],
            ["9 Place Royale","2 étage",73641,"Saint-Quentin","Lorraine","France"],
            ["162 Allée Joubert","Apt. 991",4052,"Colmar","Midi-Pyrénées","France"],
            ["99 Quai du Dahomey","0 étage",91413,"Caen","Alsace","France"],
            ["6470 Quai du Faubourg Saint-Honoré","Apt. 281",26719,"Nancy","Rhône-Alpes","France"],
            ["984 Avenue du Faubourg Saint-Honoré","2 étage",42680,"Dunkerque14","Nord-Pas-de-Calais","France"],
            ["9847 Voie de la Pompe","Apt. 889",34286,"Saint-Quentin","Rhône-Alpes","France"],
            ["975 Avenue de Paris","Apt. 186",94620,"Montpellier","Bourgogne","France"],
            ["8 Voie Adolphe Mille","Apt. 785",93234,"Le Mans","Rhône-Alpes","France"],
            ["9915 Allée du Chat-qui-Pêche","Apt. 986",55802,"Perpignan","Bourgogne","France"],
            ["10 Place du Dahomey","3 étage",48604,"Les Abymes","Champagne-Ardenne","France"],
            ["87 Allée Montorgueil","2 étage",43995,"La Seyne-sur-Mer","Rhône-Alpes","France"],
            ["7169 Boulevard Charlemagne","6 étage",92554,"Mulhouse","Picardie","France"],
            ["488 Boulevard Mouffetard","Apt. 528",10977,"Neuilly-sur-Seine","Pays de la Loire","France"],
            ["4268 Rue Zadkine","9 étage",16199,"Angers","Aquitaine","France"],
            ["0606 Avenue de la Ferronnerie","7 étage",46178,"Strasbourg","Aquitaine","France"],
            ["1 Quai de l'Odéon","Apt. 381",2067,"Issy-les-Moulineaux","Rhône-Alpes","France"],
            ["034 Boulevard du Faubourg-Saint-Denis","3 étage",16463,"Pau","Bretagne","France"],
            ["88 Impasse de l'Abbaye","4 étage",87453,"Niort","Basse-Normandie","France"],
            ["7 Place Saint-Honoré","8 étage",70617,"Nîmes","Lorraine","France"],
            ["74 Voie Saint-Bernard","Apt. 589",75130,"Courbevoie","Aquitaine","France"],
            ["58 Avenue d'Assas","9 étage",8590,"Nancy","Corse","France"],
            ["121 Avenue Saint-Séverin","4 étage",42584,"Saint-Nazaire","Poitou-Charentes","France"],
            ["1926 Rue de la Paix","Apt. 382",87366,"Cergy","Provence-Alpes-Côte d'Azur","France"],
            ["0151 Passage d'Abbeville","6 étage",87117,"Nantes","Limousin","France"],
            ["6 Rue de Tilsitt","Apt. 505",39099,"Saint-Maur-des-Fossés","Île-de-France","France"],
            ["81 Place de Montmorency","Apt. 581",14020,"Le Tampon","Champagne-Ardenne","France"],
            ["326 Rue de Caumartin","2 étage",99093,"Besançon","Auvergne","France"],
            ["03 Passage de Solférino","6 étage",51666,"Colmar","Rhône-Alpes","France"],
            ["7 Rue de Seine","4 étage",80312,"Toulouse","Haute-Normandie","France"],
            ["7969 Voie du Havre","9 étage",38246,"Troyes","Provence-Alpes-Côte d'Azur","France"],
            ["4525 Place de la Paix","8 étage",78227,"Vitry-sur-Seine","Île-de-France","France"],
            ["4 Quai Adolphe Mille","2 étage",6984,"Saint-Nazaire","Nord-Pas-de-Calais","France"],
            ["895 Voie des Lombards","Apt. 219",55931,"Limoges","Midi-Pyrénées","France"],
            ["191 Rue Saint-Bernard","7 étage",77705,"Brest","Alsace","France"],
            ["845 Avenue d'Alésia","Apt. 789",95788,"Avignon","Basse-Normandie","France"],
            ["37 Impasse de Solférino","6 étage",67488,"Saint-Denis","Auvergne","France"],
            ["308 Boulevard des Saussaies","4 étage",91646,"Dunkerque14","Auvergne","France"],
            ["5 Allée de la Pompe","Apt. 189",17662,"Asnières-sur-Seine","Île-de-France","France"],
            ["221 Rue des Rosiers","Apt. 026",48554,"Villeurbanne","Poitou-Charentes","France"],
            ["7 Voie Charlemagne","Apt. 628",51664,"Toulouse","Bourgogne","France"],
            ["07 Rue Saint-Denis","Apt. 273",77751,"La Seyne-sur-Mer","Basse-Normandie","France"],
            ["9 Passage du Faubourg Saint-Honoré","Apt. 561",82515,"Nancy","Alsace","France"],
            ["1 Place du Bac","Apt. 401",6545,"Toulon","Auvergne","France"],
            ["449 Boulevard de Provence","0 étage",49807,"Mulhouse","Rhône-Alpes","France"],
            ["4 Voie des Grands Augustins","Apt. 467",26136,"Dijon","Lorraine","France"],
            ["5616 Boulevard de Seine","1 étage",62614,"Limoges","Centre","France"],
            ["21 Rue de Paris","Apt. 707",19914,"Quimper","Rhône-Alpes","France"],
            ["23 Quai des Rosiers","Apt. 012",55436,"La Rochelle","Bourgogne","France"],
            ["89 Boulevard Molière","1 étage",84792,"Reims","Lorraine","France"],
            ["630 Passage Saint-Séverin","Apt. 519",49927,"La Rochelle","Pays de la Loire","France"],
            ["3 Place La Boétie","Apt. 937",93225,"Montreuil","Champagne-Ardenne","France"],
            ["206 Allée Molière","3 étage",46981,"La Rochelle","Picardie","France"],
            ["1 Rue Lepic","Apt. 113",86796,"Colombes","Pays de la Loire","France"],
            ["235 Voie de la Victoire","Apt. 222",54259,"Nîmes","Nord-Pas-de-Calais","France"],
            ["393 Passage Lepic","3 étage",56999,"Cholet","Franche-Comté","France"],
            ["5 Place de la Paix","Apt. 812",19031,"Caen","Nord-Pas-de-Calais","France"],
            ["1 Boulevard de Caumartin","8 étage",13045,"Amiens","Rhône-Alpes","France"],
            ["9 Passage Vaneau","Apt. 409",71954,"Saint-Denis","Basse-Normandie","France"],
            ["405 Place de la Bûcherie","8 étage",12863,"Antony","Haute-Normandie","France"],
            ["7323 Allée Saint-Bernard","0 étage",75622,"Versailles","Limousin","France"],
            ["53 Rue Saint-Honoré","Apt. 809",85153,"Troyes","Midi-Pyrénées","France"],
            ["1 Place Pierre Charron","1 étage",77460,"Mérignac","Île-de-France","France"],
            ["4047 Rue de Richelieu","2 étage",11171,"Cannes","Midi-Pyrénées","France"],
            ["46 Allée Charlemagne","Apt. 462",15947,"Toulon","Aquitaine","France"],
            ["6 Passage des Francs-Bourgeois","3 étage",27401,"Antony","Limousin","France"],
            ["93 Voie du Faubourg Saint-Honoré","Apt. 937",78702,"Champigny-sur-Marne","Haute-Normandie","France"],
            ["4851 Allée de la Pompe","Apt. 434",26342,"Antibes","Auvergne","France"],
            ["89 Impasse Saint-Bernard","Apt. 806",45589,"Lorient","Pays de la Loire","France"],
            ["072 Allée Monsieur-le-Prince","8 étage",95954,"Saint-Paul","Île-de-France","France"],
            ["430 Passage Vaneau","Apt. 523",11134,"Béziers","Bourgogne","France"],
            ["92 Boulevard des Rosiers","5 étage",20897,"Saint-Denis","Pays de la Loire","France"],
            ["577 Boulevard Montorgueil","Apt. 449",36529,"Brest","Rhône-Alpes","France"],
            ["8 Avenue de Presbourg","3 étage",22690,"Neuilly-sur-Seine","Haute-Normandie","France"],
            ["4519 Rue Saint-Dominique","Apt. 794",85427,"Créteil","Nord-Pas-de-Calais","France"],
            ["304 Place de Vaugirard","Apt. 963",55926,"Clichy","Franche-Comté","France"],
            ["5 Quai Delesseux","Apt. 235",44620,"Sarcelles","Limousin","France"],
            ["69 Allée de Rivoli","Apt. 919",29176,"Orléans","Poitou-Charentes","France"],
            ["2 Allée d'Orsel","6 étage",79145,"Vitry-sur-Seine","Languedoc-Roussillon","France"],
            ["311 Rue des Lombards","Apt. 981",37370,"Nice","Bretagne","France"],
            ["7951 Place des Saussaies","8 étage",15287,"Villeurbanne","Centre","France"],
            ["7 Avenue des Rosiers","1 étage",98754,"Dijon","Champagne-Ardenne","France"],
            ["03 Avenue de Montmorency","2 étage",67848,"Pessac","Alsace","France"],
            ["380 Place de Vaugirard","9 étage",33219,"Saint-Quentin","Corse","France"],
            ["38 Place du Havre","7 étage",87189,"Saint-Quentin","Pays de la Loire","France"],
            ["818 Voie Mouffetard","Apt. 644",10184,"Grenoble","Pays de la Loire","France"],
            ["306 Quai Pierre Charron","Apt. 413",616,"Argenteuil","Bretagne","France"],
            ["903 Avenue Pastourelle","0 étage",62717,"Vitry-sur-Seine","Aquitaine","France"],
            ["911 Avenue de Solférino","Apt. 085",4531,"Dunkerque14","Bretagne","France"],
            ["98 Avenue La Boétie","9 étage",86205,"Villeneuve-d'Ascq","Corse","France"],
            ["49 Voie d'Argenteuil","Apt. 994",23367,"Roubaix","Corse","France"],
            ["799 Allée Adolphe Mille","3 étage",60375,"Poitiers","Provence-Alpes-Côte d'Azur","France"],
            ["5 Impasse de Nesle","Apt. 008",81753,"Argenteuil","Aquitaine","France"],
            ["59 Passage de Richelieu","Apt. 854",223,"Montauban","Midi-Pyrénées","France"],
            ["717 Passage Royale","Apt. 746",47156,"La Seyne-sur-Mer","Auvergne","France"],
            ["6 Avenue de Montmorency","6 étage",43945,"Saint-Pierre","Champagne-Ardenne","France"],
            ["7033 Place des Francs-Bourgeois","2 étage",84493,"Angers","Midi-Pyrénées","France"],
            ["715 Passage de la Chaussée-d'Antin","Apt. 413",88956,"Ajaccio","Centre","France"],
            ["6 Boulevard de Provence","8 étage",83020,"Asnières-sur-Seine","Bourgogne","France"],
            ["027 Rue du Havre","Apt. 564",83442,"Dunkerque14","Midi-Pyrénées","France"],
            ["416 Voie Royale","Apt. 638",39148,"Grenoble","Auvergne","France"],
            ["249 Voie La Boétie","8 étage",19092,"Angers","Corse","France"],
            ["3788 Boulevard Saint-Denis","Apt. 153",5459,"Nîmes","Basse-Normandie","France"],
            ["34 Place de Vaugirard","3 étage",90917,"Rouen","Haute-Normandie","France"],
            ["795 Passage de la Paix","Apt. 721",87158,"Clichy","Basse-Normandie","France"],
            ["30 Impasse de la Harpe","Apt. 939",99850,"Angers","Auvergne","France"],
            ["03 Rue Montorgueil","Apt. 205",46471,"La Seyne-sur-Mer","Franche-Comté","France"],
            ["839 Allée de l'Odéon","5 étage",55472,"Le Tampon","Languedoc-Roussillon","France"],
            ["4 Quai Monsieur-le-Prince","Apt. 706",12619,"Fort-de-France","Rhône-Alpes","France"],
            ["67 Voie de Paris","6 étage",97478,"Fort-de-France","Limousin","France"],
            ["15 Rue des Grands Augustins","2 étage",89467,"Rennes","Franche-Comté","France"],
            ["0776 Impasse Mouffetard","Apt. 401",40568,"Rouen","Île-de-France","France"],
            ["2196 Place Royale","Apt. 360",69204,"Cannes","Île-de-France","France"],
            ["2 Voie Saint-Denis","2 étage",97084,"Saint-Étienne","Nord-Pas-de-Calais","France"],
            ["7 Allée Pierre Charron","7 étage",11002,"Calais","Poitou-Charentes","France"],
            ["8 Place de Presbourg","Apt. 817",48878,"Beauvais","Lorraine","France"],
            ["5487 Avenue de Caumartin","1 étage",90059,"Dijon","Limousin","France"],
            ["7 Avenue de la Victoire","Apt. 319",51989,"Lille","Picardie","France"],
            ["4188 Passage Adolphe Mille","Apt. 957",69052,"Lyon","Centre","France"],
            ["05 Avenue des Panoramas","9 étage",44792,"Aulnay-sous-Bois","Languedoc-Roussillon","France"],
            ["6808 Passage de l'Odéon","9 étage",45573,"Saint-Étienne","Picardie","France"],
            ["1 Boulevard de Nesle","Apt. 202",98096,"Ajaccio","Basse-Normandie","France"],
            ["67 Avenue de la Victoire","Apt. 094",87326,"Toulon","Picardie","France"],
            ["3615 Place Saint-Séverin","Apt. 901",74669,"Rouen","Franche-Comté","France"],
            ["2007 Impasse de Rivoli","0 étage",5793,"Valence","Bourgogne","France"],
            ["320 Rue Laffitte","1 étage",65174,"Paris","Centre","France"],
            ["3294 Avenue de Solférino","8 étage",23981,"Nantes","Midi-Pyrénées","France"],
            ["38 Quai des Lombards","3 étage",11456,"Angers","Alsace","France"],
            ["4014 Impasse La Boétie","Apt. 029",45769,"Vitry-sur-Seine","Lorraine","France"],
            ["5920 Place de Caumartin","7 étage",76665,"Nancy","Midi-Pyrénées","France"],
            ["49 Rue de Caumartin","3 étage",95028,"Poitiers","Bretagne","France"],
            ["1260 Quai de Solférino","5 étage",5790,"Asnières-sur-Seine","Nord-Pas-de-Calais","France"],
            ["2 Boulevard d'Assas","Apt. 605",22111,"Rouen","Haute-Normandie","France"],
            ["3126 Allée de Solférino","Apt. 679",49970,"Aulnay-sous-Bois","Corse","France"],
            ["359 Voie Montorgueil","9 étage",99368,"Brest","Pays de la Loire","France"],
            ["546 Rue d'Alésia","Apt. 195",14780,"Aulnay-sous-Bois","Languedoc-Roussillon","France"],
            ["30 Passage Saint-Jacques","7 étage",37648,"Cayenne","Champagne-Ardenne","France"],
            ["83 Passage Bonaparte","Apt. 859",46568,"Brest","Pays de la Loire","France"],
            ["633 Voie d'Argenteuil","8 étage",43042,"Calais","Languedoc-Roussillon","France"],
            ["72 Allée de Solférino","8 étage",41059,"Saint-Pierre","Bourgogne","France"],
            ["4893 Quai Du Sommerard","Apt. 875",82476,"Saint-Denis","Champagne-Ardenne","France"],
            ["6686 Place de l'Abbaye","7 étage",10908,"Colmar","Pays de la Loire","France"],
            ["06 Boulevard des Saussaies","Apt. 258",74726,"Champigny-sur-Marne","Aquitaine","France"],
            ["335 Voie des Lombards","Apt. 041",62028,"Champigny-sur-Marne","Corse","France"],
            ["2882 Allée Bonaparte","7 étage",95770,"Metz","Auvergne","France"],
            ["769 Avenue Charlemagne","4 étage",93256,"Angers","Basse-Normandie","France"],
            ["7 Quai des Panoramas","Apt. 071",69901,"Nantes","Haute-Normandie","France"],
            ["841 Allée d'Orsel","1 étage",63414,"Saint-Denis","Centre","France"],
            ["6 Allée de Tilsitt","Apt. 084",57472,"Tourcoing","Centre","France"],
            ["2 Boulevard d'Abbeville","7 étage",463,"Niort","Languedoc-Roussillon","France"],
            ["23 Allée des Lombards","2 étage",13078,"Grenoble","Auvergne","France"],
            ["4 Rue Vaneau","4 étage",38940,"Mérignac","Île-de-France","France"],
            ["2 Voie de Montmorency","Apt. 927",15025,"Valence","Bourgogne","France"],
            ["4 Allée Laffitte","1 étage",98310,"Orléans","Bourgogne","France"],
            ["8909 Avenue Joubert","Apt. 221",97459,"Saint-Denis","Champagne-Ardenne","France"],
            ["246 Place de Provence","Apt. 774",64282,"Bordeaux","Basse-Normandie","France"],
            ["7656 Impasse de Caumartin","Apt. 187",21539,"Nantes","Nord-Pas-de-Calais","France"],
            ["4677 Place de la Huchette","Apt. 878",80842,"Créteil","Languedoc-Roussillon","France"],
            ["04 Passage Saint-Dominique","2 étage",9664,"Nîmes","Limousin","France"],
            ["1675 Impasse de Presbourg","Apt. 576",13251,"Paris","Île-de-France","France"],
            ["459 Allée du Dahomey","Apt. 069",43654,"Le Mans","Alsace","France"],
            ["51 Allée de la Chaussée-d'Antin","3 étage",5490,"Le Tampon","Nord-Pas-de-Calais","France"],
            ["7475 Allée Mouffetard","3 étage",95712,"Rouen","Aquitaine","France"],
            ["12 Avenue de l'Abbaye","Apt. 373",6340,"Colombes","Centre","France"],
            ["4 Rue de Paris","Apt. 468",10943,"Toulouse","Bretagne","France"],
            ["873 Place Zadkine","Apt. 633",51151,"Noisy-le-Grand","Nord-Pas-de-Calais","France"],
            ["56 Passage de Provence","Apt. 686",24966,"Nancy","Bretagne","France"],
            ["0021 Rue Saint-Bernard","5 étage",85341,"Cholet","Corse","France"],
            ["4686 Quai de la Bûcherie","0 étage",33593,"Toulouse","Pays de la Loire","France"],
            ["44 Rue du Bac","1 étage",56717,"Orléans","Bretagne","France"],
            ["3261 Quai de la Victoire","Apt. 455",30283,"Aulnay-sous-Bois","Picardie","France"],
            ["3792 Quai Saint-Jacques","6 étage",79755,"Ajaccio","Centre","France"],
            ["960 Boulevard de Tilsitt","Apt. 332",95300,"Saint-Maur-des-Fossés","Poitou-Charentes","France"],
            ["6 Impasse de Tilsitt","Apt. 831",20981,"Antony","Haute-Normandie","France"],
            ["9211 Quai d'Assas","7 étage",14914,"Besançon","Pays de la Loire","France"],
            ["2 Impasse des Rosiers","Apt. 567",50161,"Lille","Haute-Normandie","France"],
            ["09 Avenue Joubert","1 étage",56594,"Tourcoing","Île-de-France","France"],
            ["20 Voie de la Victoire","3 étage",98725,"Noisy-le-Grand","Haute-Normandie","France"],
            ["3501 Passage de Caumartin","Apt. 551",29756,"Drancy","Limousin","France"],
            ["6 Passage Marcadet","Apt. 868",42502,"Nîmes","Centre","France"],
            ["9049 Allée de Caumartin","Apt. 384",59645,"Vénissieux","Lorraine","France"],
            ["28 Allée du Bac","9 étage",80467,"Villejuif","Pays de la Loire","France"],
            ["3269 Voie Saint-Séverin","Apt. 926",81212,"Versailles","Provence-Alpes-Côte d'Azur","France"],
            ["0126 Voie d'Assas","Apt. 455",51138,"Caen","Franche-Comté","France"],
            ["70 Passage Royale","Apt. 597",2493,"Colmar","Poitou-Charentes","France"],
            ["5576 Allée La Boétie","7 étage",81186,"Nice","Nord-Pas-de-Calais","France"],
            ["3 Impasse de l'Abbaye","8 étage",8679,"Tours","Picardie","France"],
            ["040 Boulevard de Presbourg","Apt. 023",81421,"Angers","Île-de-France","France"],
            ["60 Voie des Francs-Bourgeois","Apt. 376",79264,"Nanterre","Franche-Comté","France"],
            ["7370 Boulevard du Bac","6 étage",31473,"Dunkerque14","Franche-Comté","France"],
            ["5 Quai de Caumartin","Apt. 371",34189,"Le Havre","Nord-Pas-de-Calais","France"],
            ["11 Quai des Panoramas","4 étage",73842,"Bordeaux","Picardie","France"],
            ["054 Avenue de Paris","Apt. 765",53979,"Amiens","Pays de la Loire","France"],
            ["8561 Boulevard Saint-Bernard","5 étage",43680,"Lyon","Auvergne","France"],
            ["873 Quai de la Ferronnerie","Apt. 418",3772,"Sarcelles","Bourgogne","France"],
            ["510 Rue Saint-Bernard","Apt. 537",83810,"Drancy","Limousin","France"],
            ["2700 Rue de l'Odéon","Apt. 732",57377,"Cholet","Basse-Normandie","France"],
            ["931 Passage Bonaparte","2 étage",16493,"Le Tampon","Corse","France"],
            ["7136 Avenue d'Assas","7 étage",78877,"Nantes","Corse","France"],
            ["1859 Allée Marcadet","Apt. 384",43098,"Saint-Denis","Franche-Comté","France"],
            ["4 Voie de Paris","6 étage",43001,"Valence","Picardie","France"],
            ["8708 Voie de Provence","8 étage",68484,"Cayenne","Île-de-France","France"],
            ["082 Avenue Delesseux","Apt. 182",39401,"Angers","Centre","France"],
            ["5598 Impasse de Caumartin","0 étage",21636,"Aulnay-sous-Bois","Midi-Pyrénées","France"],
            ["9627 Voie Adolphe Mille","8 étage",71563,"Nancy","Bretagne","France"],
            ["6 Rue du Bac","0 étage",85094,"Issy-les-Moulineaux","Auvergne","France"],
            ["88 Allée Saint-Jacques","4 étage",47258,"Dunkerque14","Corse","France"],
            ["4 Place Adolphe Mille","Apt. 740",77629,"Montreuil","Nord-Pas-de-Calais","France"],
            ["5169 Impasse de la Pompe","3 étage",34590,"Dijon","Provence-Alpes-Côte d'Azur","France"],
            ["9 Allée Vaneau","Apt. 314",41937,"La Rochelle","Bretagne","France"],
            ["336 Boulevard de Caumartin","9 étage",11879,"Limoges","Corse","France"],
            ["807 Voie d'Orsel","Apt. 753",10201,"Perpignan","Poitou-Charentes","France"],
            ["62 Avenue Royale","0 étage",76240,"Poitiers","Alsace","France"],
            ["34 Rue des Lombards","6 étage",23249,"Toulouse","Languedoc-Roussillon","France"],
            ["151 Place de la Harpe","Apt. 014",35347,"Chambéry","Rhône-Alpes","France"],
            ["6 Place de l'Abbaye","Apt. 149",77816,"Levallois-Perret","Provence-Alpes-Côte d'Azur","France"],
            ["75 Boulevard de Presbourg","1 étage",11529,"Nanterre","Alsace","France"],
            ["4748 Place Vaneau","Apt. 453",97519,"Strasbourg","Basse-Normandie","France"],
            ["5562 Quai d'Orsel","Apt. 111",52390,"Colombes","Bretagne","France"],
            ["360 Allée de Richelieu","Apt. 457",73215,"Nanterre","Lorraine","France"],
            ["14 Rue de Caumartin","4 étage",35293,"Fort-de-France","Pays de la Loire","France"],
            ["428 Rue de l'Abbaye","3 étage",9110,"Lille","Bretagne","France"],
            ["7 Place du Chat-qui-Pêche","Apt. 952",37608,"Valence","Alsace","France"],
            ["0 Allée de Vaugirard","Apt. 301",62280,"Quimper","Midi-Pyrénées","France"],
            ["999 Quai Molière","Apt. 487",51905,"Tourcoing","Bretagne","France"],
            ["81 Impasse des Saussaies","5 étage",74907,"Champigny-sur-Marne","Midi-Pyrénées","France"],
            ["2 Boulevard de Rivoli","6 étage",60021,"Ivry-sur-Seine","Alsace","France"],
            ["02 Avenue Molière","Apt. 547",53283,"Saint-Denis","Bretagne","France"],
            ["127 Impasse du Havre","5 étage",11229,"Sarcelles","Poitou-Charentes","France"],
            ["1274 Passage d'Orsel","1 étage",32964,"Calais","Alsace","France"],
            ["142 Place Bonaparte","8 étage",23619,"Saint-Nazaire","Haute-Normandie","France"],
            ["968 Voie de Solférino","Apt. 637",37887,"Toulon","Franche-Comté","France"],
            ["71 Voie de Montmorency","4 étage",29124,"Ivry-sur-Seine","Rhône-Alpes","France"],
            ["77 Voie de la Bûcherie","Apt. 172",20334,"Lyon","Alsace","France"],
            ["220 Boulevard de la Pompe","Apt. 545",94469,"La Seyne-sur-Mer","Corse","France"],
            ["08 Voie de l'Odéon","9 étage",83964,"Boulogne-Billancourt","Picardie","France"],
            ["741 Rue du Havre","0 étage",20895,"Brest","Aquitaine","France"],
            ["521 Place Du Sommerard","Apt. 656",23012,"Rueil-Malmaison","Pays de la Loire","France"],
            ["294 Place de Paris","Apt. 668",30576,"Sarcelles","Franche-Comté","France"],
            ["29 Place Saint-Séverin","3 étage",58881,"Antony","Franche-Comté","France"],
            ["09 Avenue des Francs-Bourgeois","7 étage",16468,"Paris","Corse","France"],
            ["5336 Rue Monsieur-le-Prince","Apt. 933",21680,"Bourges","Poitou-Charentes","France"],
            ["8 Rue Pastourelle","0 étage",50406,"Lille","Nord-Pas-de-Calais","France"],
            ["06 Avenue Laffitte","4 étage",80439,"Brest","Île-de-France","France"],
            ["650 Place du Faubourg-Saint-Denis","8 étage",11111,"Montreuil","Basse-Normandie","France"],
            ["1007 Allée de Vaugirard","Apt. 543",96927,"Calais","Auvergne","France"],
            ["90 Allée d'Orsel","1 étage",38632,"Montauban","Centre","France"],
            ["9 Rue des Lombards","Apt. 393",87386,"Nantes","Bretagne","France"],
            ["2165 Quai d'Abbeville","4 étage",62383,"Fort-de-France","Rhône-Alpes","France"],
            ["1 Passage Dauphine","0 étage",24996,"Mérignac","Lorraine","France"],
            ["9 Impasse Royale","Apt. 441",68512,"Montreuil","Franche-Comté","France"],
            ["7 Quai Saint-Denis","9 étage",28669,"Ivry-sur-Seine","Languedoc-Roussillon","France"],
            ["900 Impasse des Panoramas","0 étage",60984,"Mulhouse","Auvergne","France"],
            ["83 Rue Saint-Bernard","Apt. 525",76045,"Poitiers","Corse","France"],
            ["430 Voie d'Argenteuil","Apt. 558",4263,"Mérignac","Centre","France"],
            ["9268 Place Monsieur-le-Prince","0 étage",241,"Beauvais","Provence-Alpes-Côte d'Azur","France"],
            ["1 Place du Bac","Apt. 865",63277,"Nanterre","Bourgogne","France"],
            ["10 Avenue Charlemagne","Apt. 613",52926,"Le Tampon","Basse-Normandie","France"],
            ["2619 Impasse d'Abbeville","7 étage",97140,"Rouen","Franche-Comté","France"],
            ["0157 Allée Pierre Charron","4 étage",56232,"Villeurbanne","Provence-Alpes-Côte d'Azur","France"],
            ["538 Quai de la Ferronnerie","Apt. 066",60462,"Beauvais","Poitou-Charentes","France"],
            ["0 Rue de Seine","Apt. 589",68866,"Champigny-sur-Marne","Pays de la Loire","France"],
            ["3924 Impasse d'Argenteuil","Apt. 394",53099,"Pau","Champagne-Ardenne","France"],
            ["6203 Place de Tilsitt","6 étage",6412,"Champigny-sur-Marne","Languedoc-Roussillon","France"],
            ["115 Impasse Monsieur-le-Prince","1 étage",38590,"Argenteuil","Midi-Pyrénées","France"],
            ["363 Impasse des Rosiers","8 étage",57744,"Villeneuve-d'Ascq","Basse-Normandie","France"],
            ["68 Place du Faubourg-Saint-Denis","Apt. 760",58947,"Montpellier","Languedoc-Roussillon","France"],
            ["004 Impasse de Paris","0 étage",6154,"Strasbourg","Provence-Alpes-Côte d'Azur","France"],
            ["8 Passage de Paris","Apt. 662",47205,"Reims","Auvergne","France"],
            ["150 Place de la Pompe","Apt. 050",6632,"Boulogne-Billancourt","Rhône-Alpes","France"],
            ["531 Voie de la Paix","9 étage",54576,"Rennes","Poitou-Charentes","France"],
            ["181 Passage Saint-Séverin","7 étage",87737,"Cholet","Nord-Pas-de-Calais","France"],
            ["88 Impasse de la Ferronnerie","0 étage",22382,"Nîmes","Provence-Alpes-Côte d'Azur","France"],
            ["6 Passage de Nesle","3 étage",35655,"Nanterre","Champagne-Ardenne","France"],
            ["12 Voie Saint-Jacques","4 étage",29104,"Lyon","Alsace","France"],
            ["6 Avenue Pierre Charron","7 étage",1293,"Chambéry","Haute-Normandie","France"],
            ["6686 Passage du Havre","2 étage",59312,"Rueil-Malmaison","Languedoc-Roussillon","France"],
            ["2 Impasse de Tilsitt","Apt. 451",11860,"Fort-de-France","Alsace","France"],
            ["91 Avenue du Havre","3 étage",20172,"Lorient","Aquitaine","France"],
            ["9 Impasse Charlemagne","Apt. 426",1537,"Aix-en-Provence","Centre","France"],
            ["3046 Place Mouffetard","Apt. 876",98558,"Roubaix","Haute-Normandie","France"],
            ["9741 Place d'Orsel","Apt. 417",3553,"Quimper","Champagne-Ardenne","France"],
            ["8993 Allée de l'Abbaye","Apt. 411",11653,"Champigny-sur-Marne","Auvergne","France"],
            ["6 Quai de Paris","1 étage",27179,"Montpellier","Poitou-Charentes","France"],
            ["5286 Boulevard de Caumartin","Apt. 343",29521,"Rueil-Malmaison","Centre","France"],
            ["9 Passage des Panoramas","1 étage",2826,"Argenteuil","Poitou-Charentes","France"],
            ["9356 Impasse de la Chaussée-d'Antin","4 étage",80639,"Courbevoie","Picardie","France"],
            ["531 Quai d'Assas","9 étage",19263,"Le Mans","Bretagne","France"],
            ["533 Place de la Paix","Apt. 153",54017,"Saint-Étienne","Champagne-Ardenne","France"],
            ["8899 Place des Francs-Bourgeois","Apt. 815",11758,"Poitiers","Centre","France"],
            ["7826 Quai de la Ferronnerie","Apt. 468",74458,"Dijon","Centre","France"],
            ["5 Voie des Francs-Bourgeois","Apt. 750",68544,"Pessac","Champagne-Ardenne","France"],
            ["8 Rue de Montmorency","4 étage",18492,"Vitry-sur-Seine","Aquitaine","France"],
            ["0543 Passage de Seine","Apt. 994",50004,"Niort","Auvergne","France"],
            ["7 Voie du Chat-qui-Pêche","0 étage",57187,"Antibes","Franche-Comté","France"],
            ["799 Place de Presbourg","5 étage",79546,"Saint-Denis","Limousin","France"],
            ["469 Passage du Faubourg-Saint-Denis","4 étage",62605,"Versailles","Haute-Normandie","France"],
            ["1753 Quai de Provence","Apt. 024",87982,"Argenteuil","Pays de la Loire","France"],
            ["42 Boulevard Laffitte","Apt. 599",18689,"Saint-Nazaire","Île-de-France","France"],
            ["69 Rue Saint-Dominique","2 étage",60724,"Les Abymes","Aquitaine","France"],
            ["5 Impasse des Grands Augustins","8 étage",47075,"Saint-Étienne","Aquitaine","France"],
            ["5 Avenue de la Chaussée-d'Antin","Apt. 465",95300,"Nîmes","Alsace","France"],
            ["3113 Avenue Zadkine","0 étage",93000,"Paris","Champagne-Ardenne","France"],
            ["62 Avenue du Faubourg Saint-Honoré","1 étage",79661,"Nice","Rhône-Alpes","France"],
            ["049 Rue de la Victoire","1 étage",4876,"Saint-Étienne","Midi-Pyrénées","France"],
            ["393 Place des Rosiers","Apt. 074",95525,"Calais","Centre","France"],
            ["1 Allée Saint-Jacques","0 étage",11167,"Aubervilliers","Franche-Comté","France"],
            ["1 Impasse de Vaugirard","Apt. 290",12947,"Nancy","Midi-Pyrénées","France"],
            ["155 Rue Saint-Séverin","Apt. 769",90091,"Paris","Île-de-France","France"],
            ["2 Quai de Montmorency","3 étage",58193,"Saint-Paul","Champagne-Ardenne","France"],
            ["7 Passage de la Ferronnerie","Apt. 513",78416,"Angers","Lorraine","France"],
            ["7 Passage Montorgueil","0 étage",83028,"Nîmes","Bretagne","France"],
            ["9944 Impasse de Tilsitt","Apt. 505",60989,"Calais","Midi-Pyrénées","France"],
            ["2660 Place du Faubourg Saint-Honoré","3 étage",44432,"Neuilly-sur-Seine","Franche-Comté","France"],
            ["0818 Boulevard Montorgueil","Apt. 699",9262,"Cholet","Franche-Comté","France"],
            ["00 Boulevard des Francs-Bourgeois","Apt. 234",14926,"Rennes","Basse-Normandie","France"],
            ["8420 Impasse Mouffetard","Apt. 513",97774,"Beauvais","Corse","France"],
            ["9516 Passage des Grands Augustins","Apt. 351",71916,"Saint-Pierre","Alsace","France"],
            ["7844 Boulevard Pastourelle","Apt. 648",55174,"Tourcoing","Provence-Alpes-Côte d'Azur","France"],
            ["986 Boulevard de l'Odéon","1 étage",54162,"Aix-en-Provence","Aquitaine","France"],
            ["60 Impasse Saint-Dominique","Apt. 531",58785,"Noisy-le-Grand","Midi-Pyrénées","France"],
            ["615 Rue La Boétie","Apt. 534",83394,"Metz","Centre","France"],
            ["6685 Place de Presbourg","3 étage",20916,"Levallois-Perret","Provence-Alpes-Côte d'Azur","France"],
            ["93 Quai du Faubourg-Saint-Denis","Apt. 921",15039,"Rouen","Aquitaine","France"],
            ["24 Passage de l'Odéon","5 étage",71135,"Saint-Pierre","Auvergne","France"],
            ["205 Impasse de Seine","6 étage",80191,"Villejuif","Centre","France"],
            ["148 Allée de Solférino","Apt. 421",18230,"Champigny-sur-Marne","Midi-Pyrénées","France"],
            ["122 Impasse de l'Abbaye","5 étage",82859,"Ajaccio","Auvergne","France"],
            ["3490 Voie des Francs-Bourgeois","7 étage",53833,"Amiens","Bourgogne","France"],
            ["3 Place des Panoramas","3 étage",13151,"La Rochelle","Franche-Comté","France"],
            ["74 Quai du Chat-qui-Pêche","Apt. 011",40063,"Saint-Denis","Provence-Alpes-Côte d'Azur","France"],
            ["9008 Impasse des Grands Augustins","Apt. 022",60706,"Dunkerque14","Pays de la Loire","France"],
            ["7 Quai d'Abbeville","3 étage",40012,"Calais","Picardie","France"],
            ["73 Place du Faubourg Saint-Honoré","Apt. 030",71735,"Aulnay-sous-Bois","Pays de la Loire","France"],
            ["0 Avenue de l'Odéon","Apt. 327",26453,"Clichy","Franche-Comté","France"],
            ["6 Impasse Adolphe Mille","Apt. 434",13939,"Grenoble","Centre","France"],
            ["99 Boulevard Marcadet","5 étage",43927,"Caen","Languedoc-Roussillon","France"],
            ["9 Boulevard Oberkampf","Apt. 224",64058,"Toulon","Rhône-Alpes","France"],
            ["1876 Boulevard de Paris","Apt. 234",93074,"Chambéry","Bourgogne","France"],
            ["46 Voie de la Chaussée-d'Antin","Apt. 616",1577,"Poitiers","Midi-Pyrénées","France"],
            ["5 Impasse de la Harpe","2 étage",57134,"Vénissieux","Bretagne","France"],
            ["9584 Voie des Saussaies","Apt. 076",3731,"Saint-Denis","Pays de la Loire","France"],
            ["2 Rue du Faubourg-Saint-Denis","9 étage",63961,"Aubervilliers","Lorraine","France"],
            ["4 Voie Saint-Jacques","Apt. 336",77347,"Saint-Pierre","Limousin","France"],
            ["48 Allée du Havre","3 étage",38087,"Quimper","Lorraine","France"],
            ["389 Voie de Richelieu","Apt. 966",8997,"Drancy","Bourgogne","France"],
            ["116 Rue de Seine","Apt. 056",95571,"Grenoble","Nord-Pas-de-Calais","France"],
            ["46 Avenue Saint-Denis","Apt. 504",29955,"Noisy-le-Grand","Haute-Normandie","France"],
            ["7 Boulevard Saint-Honoré","3 étage",23028,"Clichy","Poitou-Charentes","France"],
            ["96 Rue de Vaugirard","Apt. 609",54345,"Vitry-sur-Seine","Auvergne","France"],
            ["588 Rue Saint-Bernard","9 étage",62219,"Noisy-le-Grand","Basse-Normandie","France"],
            ["3118 Quai Monsieur-le-Prince","Apt. 553",41262,"Cergy","Poitou-Charentes","France"],
            ["5227 Quai Monsieur-le-Prince","4 étage",17920,"Villejuif","Île-de-France","France"],
            ["2 Boulevard Pastourelle","7 étage",69935,"Neuilly-sur-Seine","Limousin","France"],
            ["156 Place de Paris","5 étage",56075,"Nancy","Bourgogne","France"],
            ["807 Place des Panoramas","7 étage",37704,"Saint-Denis","Basse-Normandie","France"],
            ["1766 Quai de Seine","Apt. 555",42670,"Limoges","Poitou-Charentes","France"],
            ["871 Passage de Paris","Apt. 183",89877,"Niort","Franche-Comté","France"],
            ["682 Passage des Francs-Bourgeois","Apt. 766",38360,"Niort","Languedoc-Roussillon","France"],
            ["1 Impasse du Bac","6 étage",31241,"Vénissieux","Midi-Pyrénées","France"],
            ["60 Allée des Lombards","2 étage",57125,"Tourcoing","Provence-Alpes-Côte d'Azur","France"],
            ["9 Rue Pastourelle","Apt. 777",55221,"Sarcelles","Poitou-Charentes","France"],
            ["9 Voie de Montmorency","Apt. 858",83991,"Metz","Aquitaine","France"],
            ["3 Voie de Solférino","9 étage",20034,"Courbevoie","Poitou-Charentes","France"],
            ["6963 Quai de la Huchette","Apt. 966",4277,"Rueil-Malmaison","Centre","France"],
            ["5 Place du Havre","2 étage",78247,"Mérignac","Corse","France"],
            ["386 Impasse Monsieur-le-Prince","4 étage",66469,"Courbevoie","Alsace","France"],
            ["0 Avenue Monsieur-le-Prince","3 étage",99271,"Clichy","Corse","France"],
            ["4002 Place de Rivoli","Apt. 130",34034,"Nice","Lorraine","France"],
            ["0 Boulevard de la Harpe","6 étage",10992,"Rouen","Corse","France"],
            ["622 Quai des Francs-Bourgeois","6 étage",91169,"Rennes","Champagne-Ardenne","France"],
            ["308 Quai du Dahomey","1 étage",29368,"Saint-Denis","Bretagne","France"],
            ["2 Boulevard Saint-Dominique","Apt. 062",54539,"Pessac","Auvergne","France"],
            ["2012 Avenue Du Sommerard","0 étage",75970,"Caen","Haute-Normandie","France"],
            ["2 Boulevard Delesseux","Apt. 328",57195,"Reims","Aquitaine","France"],
            ["1 Boulevard Marcadet","7 étage",30553,"Orléans","Aquitaine","France"],
            ["37 Place de Presbourg","6 étage",72055,"Pessac","Limousin","France"],
            ["753 Allée Saint-Denis","7 étage",83348,"Antibes","Aquitaine","France"],
            ["3 Avenue de Nesle","Apt. 217",259,"Champigny-sur-Marne","Champagne-Ardenne","France"],
            ["82 Avenue Molière","Apt. 235",91570,"Niort","Alsace","France"],
            ["9 Boulevard de Paris","1 étage",95364,"Lyon","Nord-Pas-de-Calais","France"],
            ["43 Voie de Paris","Apt. 254",49209,"Aulnay-sous-Bois","Basse-Normandie","France"],
            ["724 Allée de la Victoire","3 étage",2125,"Grenoble","Lorraine","France"],
            ["90 Rue Monsieur-le-Prince","4 étage",29156,"Troyes","Haute-Normandie","France"],
            ["9 Impasse Saint-Denis","Apt. 326",65218,"Bourges","Corse","France"],
            ["6458 Passage d'Orsel","3 étage",64267,"Paris","Haute-Normandie","France"],
            ["0631 Quai Saint-Jacques","3 étage",80303,"La Seyne-sur-Mer","Lorraine","France"],
            ["61 Impasse Saint-Honoré","0 étage",98474,"Roubaix","Auvergne","France"],
            ["3707 Passage de la Bûcherie","Apt. 573",9811,"Poitiers","Bourgogne","France"],
            ["7666 Place des Panoramas","3 étage",94479,"Champigny-sur-Marne","Franche-Comté","France"],
            ["2 Allée de la Chaussée-d'Antin","Apt. 176",20159,"Rouen","Île-de-France","France"],
            ["8 Boulevard Dauphine","3 étage",29663,"Caen","Auvergne","France"],
            ["373 Voie du Faubourg-Saint-Denis","0 étage",6776,"Montauban","Lorraine","France"],
            ["7645 Passage Oberkampf","Apt. 335",21909,"Saint-Denis","Languedoc-Roussillon","France"],
            ["9 Boulevard de la Harpe","Apt. 199",21912,"Aix-en-Provence","Languedoc-Roussillon","France"],
            ["029 Avenue de Provence","3 étage",17063,"Pau","Basse-Normandie","France"],
            ["85 Passage des Francs-Bourgeois","Apt. 230",40547,"Brest","Île-de-France","France"],
            ["9391 Boulevard de la Paix","Apt. 644",54221,"Saint-Pierre","Picardie","France"],
            ["74 Allée de la Pompe","1 étage",37635,"Roubaix","Rhône-Alpes","France"],
            ["709 Avenue du Faubourg-Saint-Denis","Apt. 017",30822,"Toulon","Limousin","France"],
            ["9 Quai Saint-Bernard","Apt. 585",35566,"Valence","Franche-Comté","France"],
            ["856 Rue Bonaparte","Apt. 026",22918,"Nîmes","Poitou-Charentes","France"],
            ["2 Allée Du Sommerard","6 étage",87778,"Levallois-Perret","Poitou-Charentes","France"],
            ["62 Quai de l'Abbaye","Apt. 371",22134,"Issy-les-Moulineaux","Provence-Alpes-Côte d'Azur","France"],
            ["4004 Rue Lepic","3 étage",38019,"Pessac","Alsace","France"],
        ];
    }
}
