#!/bin/bash
set -e

if ( ip -4 route list match 0/0 &>/dev/null );then
  ip -4 route list match 0/0 \
  | awk '{print $3" host.docker.internal"}' >> /etc/hosts;
fi


# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
        set -- php-fpm "$@"
fi

exec "$@"