name: Build Docker FrankenPHP image

on:
  push:
    branches:
      - "main"
    tags:
      - '*'
    paths:
      - .gitattributes
      - .github/workflows/build-and-publish-franken-image.yml
      - docker/franken-image/Dockerfile
      - composer.*
      - src/**

env:
  IMAGE_NAME: db-tools-bundle

jobs:
  build-and-push-image:
    name: Push Docker FrankenPHP image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: makinacorpus/db-tools-bundle

    - name: Build and push Docker image
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        file: docker/franken-image/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags == 'main' && 'unstable' || steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
